from fastapi import APIRouter, HTTPException
import httpx

router = APIRouter(prefix="/manifests", tags=["manifests"])

@router.get("/{run_id}")
async def get_manifest(run_id: str):
    """
    In a real app, this would fetch the signed URL or directly 
    return the JSON manifest generated by Genblaze from B2.
    For MVP, we return a mock manifest reflecting the pipeline structure.
    """
    mock_manifest = {
        "run_id": run_id,
        "status": "COMPLETED",
        "assets": [
            {
                "type": "image",
                "model": "nano-banana-2",
                "url": f"https://f000.backblazeb2.com/file/creatorflow-bucket/assets/{run_id}/image.png"
            },
            {
                "type": "video",
                "model": "veo-3.1-fast",
                "url": f"https://f000.backblazeb2.com/file/creatorflow-bucket/assets/{run_id}/video.mp4"
            },
             {
                "type": "audio",
                "model": "lyria-3",
                "url": f"https://f000.backblazeb2.com/file/creatorflow-bucket/assets/{run_id}/audio.mp3"
            }
        ],
        "created_at": "2026-07-28T12:00:00Z",
        "completed_at": "2026-07-28T12:00:30Z"
    }
    return mock_manifest
